matrix:
  include:
    - language: c
      before_install:
        - sudo apt-get install openmpi-bin libopenmpi-dev 
      script: 
        - cd ljmd-c 
        - make check 
        - make test
    
    - language: python
      python: 3.7
      before_install:
        - sudo apt-get install openmpi-bin libopenmpi-dev 
        - pip install mpi4py
      script:
        - cd ljmd-c
        - make mpi
        - cd src_py
        - mpiexec -np 1 python3 main_mpi.py < ../examples/argon_108.inp

